name: .NET Azure Function CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Restore dependencies
        run: dotnet restore FunctionAppValidaDuplicidadeEmail.sln

      - name: Build
        run: dotnet build FunctionAppValidaDuplicidadeEmail.sln --configuration Release

      - name: Run Unit Tests
        run: dotnet test FunctionAppValidaDuplicidadeEmail.Test/FunctionAppValidaDuplicidadeEmail.Test.csproj --configuration Release --logger "console;verbosity=detailed"

      - name: Publish Azure Function
        run: dotnet publish FunctionAppValidaDuplicidadeEmail/FunctionAppValidaDuplicidadeEmail.csproj --configuration Release --output FunctionAppValidaDuplicidadeEmail/publish

      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'consulta-contato-function'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: 'FunctionAppValidaDuplicidadeEmail/publish'
